{
 "title": "TPME",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Exporter request rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "request_rate" }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "responseTime" }
   ]
  },
  {
   "title": "Metric rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(metric_rate{deployment=\"main\"})+sum(metric_rate{deployment=\"secondary\"})"
    }
   ]
  },
  {
   "title": "Beats exported",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(datapoints_sent{deployment=\"main\"})+sum(datapoints_sent{deployment=\"secondary\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "memory" }
   ]
  },
  {
   "title": "Amount metrics Prometheus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(metrics_prometheus{deployment=\"main\"})+sum(metrics_prometheus{deployment=\"secondary\"})"
    }
   ]
  },
  {
   "title": "Total Query duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    { "expr": "max(query_time)" },
    { "expr": "max(send_duration)" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cpu_usage" }
   ]
  }
 ]
}