apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tme-operator
  namespace: tme 
subjects:
- kind: ServiceAccount
  name: tme-operator
  namespace: tme
roleRef:
  kind: Role
  name: role-tme 
  apiGroup: rbac.authorization.k8s.io