apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tme-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tme-role-cluster
subjects:
  - kind: ServiceAccount
    name: tme-operator
    namespace: tme 