apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: triplemonitoringengines.unipi.gr
spec:
  scope: Namespaced
  group: unipi.gr
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: TripleMonitoringEngine
    plural: triplemonitoringengines
    singular: triplemonitoringengine
    shortNames:
      - tme
      - tmes
  additionalPrinterColumns:
    - name: Type
      type: string
      priority: 0
      JSONPath: .spec.type
      description: The type triple monitoring engine components