apiVersion: apps/v1
kind: Deployment
metadata:
  name: op
spec:
  selector:
    matchLabels:
      app: op
  template:
    metadata:
      labels:
        app: op
    spec:
      serviceAccountName: tme-operator
      containers:
      - image: jdtotow/tme_operator:latest
        name: op
        imagePullPolicy: Always