apiVersion: v1
kind: Service
metadata:
  name: prometheus-cluster
spec:
  selector:
    app: prometheus-cluster
  ports:
    - port: 9090
      targetPort: 9090
  externalTrafficPolicy: Local
  type: LoadBalancer