global:
  scrape_interval: 15s
  external_labels:
    replicas: prom-1
scrape_configs:
- job_name: prometheus
  scrape_interval: 12s
  static_configs:
  - targets:
    - localhost:9090
- honor_labels: true
  job_name: pushgateway
  scrape_interval: 5s
  static_configs:
  - targets:
    - pushgateway:9091
- job_name: grafana
  scrape_interval: 5s
  static_configs:
  - targets:
    - grafana:3000
- job_name: node-exporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - node-exporter:9100
