apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-prometheus-ks8
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jean-didier/volumes"