apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-prometheus-cep-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi