apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-config-claim 
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi