apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-tsdb-claim   
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
