apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-volume-qos
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/qos/volumes"