apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender
spec:
  selector:
    matchLabels:
      app: recommender
  template:
    metadata:
      labels:
        app: recommender
    spec:
      containers:
      - image: jdtotow/recommender
        name: recommender
        imagePullPolicy: Always
        env:
        - name: LOGSTASHURL
          value: "http://logstash.tme.svc.cluster.local:8081"
        ports:
        - containerPort: 7070 

---
apiVersion: v1
kind: Service
metadata:
  name: recommender
  labels:
    app: recommender
spec:
  type: ClusterIP
  ports:
  - port: 7070
    targetPort: 7070 
    protocol: TCP
  selector:
    app: recommender
