apiVersion: v1
kind: PersistentVolume
metadata:
  name: sidecar-volume-prometheus
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jean-didier/kubevolumes/sidecar"