apiVersion: v1
kind: PersistentVolume
metadata:
  name: sidecar-volume-prometheus
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jean-didier/sidecar"