apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sidecar-prometheus-volume-claim 
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi