apiVersion: unipi.gr/v1
kind: TripleMonitoringEngine
metadata:
  name: prometheus-cluster
  namespace: tme 
spec:
  type: tme-prometheus 
  prometheus:
    url: prometheus-cluster.default.svc.cluster.local 
    externals-labels: replicas 
  volume:
    name: volume-prometheus-ks8 
    claim_name: volume-prometheus-ks8-claim 