apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-manager
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jean-didier/kubevolumes/manager"