{
 "title": "Recommender",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "responseTime{BIGDATASTACK_APPID=\"grssr-recommender-0\"}"
    }
   ]
  },
  {
   "title": "Cost per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(costPerHour{appID=\"grssr\"})"
    }
   ]
  },
  {
   "title": "Memory requested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{container=\"recommender\"})"
    }
   ]
  },
  {
   "title": "Memory limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{container=\"recommender\"}"
    }
   ]
  },
  {
   "title": "CPU requested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{container=\"recommender\"}"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{container=\"recommender\"}"
    }
   ]
  }
 ]
}