FROM ubuntu:16.04
MAINTAINER JD TOTOW <totow@unipi.gr>
RUN apt-get update 
RUN apt-get install -y python3 python3-pip curl 
RUN pip3 install requests
RUN mkdir /app
RUN useradd tester
RUN chown -R tester /app 
COPY recommender_tester.py /app/app.py 
COPY start_qos.sh /app/start_qos.sh 
COPY agreement.json /app/agreement.json 
RUN chmod +x /app/start_qos.sh 
USER tester 
WORKDIR /app 
ENTRYPOINT ["python3","-u","app.py"]