{
 "title": "Dummy application",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "latency*0.001" }
   ]
  },
  {
   "title": "Throughput ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "throughput" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "memory_usage" }
   ]
  },
  {
   "title": "Latency (Orlando Test)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "latency*0.001" }
   ]
  }
 ]
}