apiVersion: apps/v1
kind: Deployment
metadata:
  name: tester
  namespace: tme 
spec:
  selector:
    matchLabels:
      app: tester
  template:
    metadata:
      labels:
        app: tester
    spec:
      containers:
      - image: jdtotow/tester
        name: tester
        imagePullPolicy: Always
        env:
        - name: FEEDBACKS_HOSTNAME
          value: "proxy.istioapp.svc:8083"
        - name: NTHREADS
          value: "1"
        - name: NREQUEST
          value: "2"
        - name: SLEEP_TIME
          value: "5"